apiVersion: v1
kind: Service
metadata:
  name: examenService
  labels:
    app: expensse-tracker
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    app: expensse-tracker
